### ISSUE TITLE
Bug in `ListResourceRecordSets` command

### ISSUE THREAD

**Issue by saschat** [memcachier/aws-route53#5]
Setting `lrrsRecordType` to `Just CNAME` in the `ListResourceRecordSets` command results in an error: `XmlException {xmlErrorMessage = "Missing Error Message"}`

**Comment by saschat** [comment]
This seems to be by design (Type can only be set if Name is set as well): http://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html

**Comment by dterei** [comment]
@saschat given this is by design, can we close this issue then?
